version: 0.0
os: linux

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
files:
  - source: /
    destination: /home/ec2-user/pump

hooks:
  BeforeInstall:
    - location: scripts/delete-before-artifacts.sh
      timeout: 300
  AfterInstall:
    - location: scripts/change-script-permissions.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/run-application.sh
      timeout: 300