spring:
  config:
    activate:
      on-profile: dev
  data:
    redis:
      host: ${REDIS_CLOUD_HOST}
      port: ${REDIS_CLOUD_PORT}
      password: ${REDIS_CLOUD_PASSWORD}
      name: ${REDIS_CLOUD_NAME}
      repositories:
        enabled: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
server:
  port: 8080